# See https://docs.giantswarm.io/reference/platform-api/chart-metadata/
# for details and background.

apiVersion: v2
# Version of the packaged app
appVersion: "1.4.0"
# Make sure your name DOES NOT end in "app" or "-app".
name: k6-operator
# Please describe what the app provides in a sentence or two.
description: A Helm chart to install the k6-operator
# URL of the GitHub repository that is the source of this Chart.yaml file.
home: https://github.com/giantswarm/k6-operator-app
# If you have an icon/logo, you should add it to https://github.com/giantswarm/web-assets
# and set the final URL here.
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
sources:
  - https://github.com/giantswarm/k6-operator-app
  - https://github.com/grafana/k6-operator/blob/main/charts/k6-operator
dependencies:
  - name: k6-operator
    alias: k6operator
    version: 4.4.1
    repository: https://grafana.github.io/helm-charts
    condition: k6operatorEnabled
version: 0.1.4
annotations:
  io.giantswarm.application.audience: giantswarm
  io.giantswarm.application.managed: "false"
  io.giantswarm.application.team: cabbage
